---
apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: {{ include "oms.cnfg.servercon" . }}-server-conf
spec:
  data: {{ .Values.serverconfBase64 }}
  description: "Server conf"
  type: serverconf