 deploy_jobschedularms:
   stage: deploy
   tags:
     - ppmrunner
   dependencies:
     - build_jobschedularms 
   script:
     - ls -ltr
     - podman rmi --force jobschedularms 
     - podman rm -f jobschedularms 
     - podman build -t jobschedularms --build-arg WAR_FILE=JobSchedulerMS.war --build-arg TOMCAT_PORT=8080 -f java11file .
     - podman run -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME -e DB_HOST=$DB_HOST -e     DB_PORT=$DB_PORT -e PEP_SVN_WRITE_USERNAME=$PEP_SVN_WRITE_USERNAME -e PEP_SVN_WRITE_PASSWORD=$PEP_SVN_WRITE_PASSWORD -d --network ppm_network --name jobschedularms -p 8110:8080 jobschedularms 
   rules:
     - if: $CI_COMMIT_BRANCH == "ppm-dev" 
       changes:
         - JobSchedulerMS/**/*
   needs:
     - job: build_jobschedularms
