 deploy_apigatewayms:
   stage: deploy
   tags:
     - ppmrunner
   dependencies:
     - build_apigatewayms 
   script:
     - ls -ltr
     - podman rmi --force apigatewayms 
     - podman rm -f apigatewayms 
     - podman build -t apigatewayms --build-arg WAR_FILE=ApiGatewayMS.jar --build-arg TOMCAT_PORT=8080 -f java8file .
     - podman run -d --network ppm_network --name apigatewayms -p 9209:8080 apigatewayms 

   rules:
     - if: $CI_COMMIT_BRANCH == "ppm-dev"
       changes:
         - ApiGatewayMS/**/* 
   needs:
     - job: build_apigatewayms

