 deploy_utilityms:
   stage: deploy
   tags:
     - ppmrunner
   dependencies:
     - build_utilityms 
   script:
     - ls -ltr
     - podman rmi --force utilityms 
     - podman rm -f utilityms 
     - podman build -t utilityms --build-arg WAR_FILE=UtilityMS.war --build-arg TOMCAT_PORT=8080 -f java11file .
     - podman run -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME -e DB_HOST=$DB_HOST -e     DB_PORT=$DB_PORT -e PEP_SVN_WRITE_USERNAME=$PEP_SVN_WRITE_USERNAME -e PEP_SVN_WRITE_PASSWORD=$PEP_SVN_WRITE_PASSWORD -d --network ppm_network --name utilityms -p 8105:8080 utilityms 

   rules:
     - if: $CI_COMMIT_BRANCH == "ppm-dev" 
       changes:
         - UtilityMS/**/*
   needs:
     - job: build_utilityms
