 deploy_accountingms:
   stage: deploy
   tags:
     - ppmrunner
   dependencies:
     - build_accountingms 
   script:
     - ls -ltr
     - podman rmi --force accountingms 
     - podman rm -f accountingms 
     - podman build -t accountingms --build-arg WAR_FILE=accountingms.war --build-arg TOMCAT_PORT=8080 -f java11file .
     - podman run -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME -e DB_HOST=$DB_HOST -e     DB_PORT=$DB_PORT -e PEP_SVN_WRITE_USERNAME=$PEP_SVN_WRITE_USERNAME -e PEP_SVN_WRITE_PASSWORD=$PEP_SVN_WRITE_PASSWORD -d --network ppm_network --name accountingms -p 8107:8080 accountingms   
   rules:
     - if: $CI_COMMIT_BRANCH == "ppm-dev" 
       changes:
         - accountingms/**/*
   needs:
     - job: build_accountingms
