 deploy_layoutms:
   stage: deploy
   tags:
     - ppmrunner
   dependencies:
     - build_layoutms 
   script:
     - ls -ltr
     - podman rmi --force layoutms 
     - podman rm -f layoutms 
     - podman build -t layoutms --build-arg WAR_FILE=LayoutMS.war --build-arg TOMCAT_PORT=8080 -f java11file .
     - podman run -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME -e DB_HOST=$DB_HOST -e     DB_PORT=$DB_PORT -e PEP_SVN_WRITE_USERNAME=$PEP_SVN_WRITE_USERNAME -e PEP_SVN_WRITE_PASSWORD=$PEP_SVN_WRITE_PASSWORD -d --network ppm_network --name layoutms -p 8096:8080 layoutms 
   rules:
     - if: $CI_COMMIT_BRANCH == "ppm-dev" 
       changes:
         - LayoutMS/**/*
   needs:
     - job: build_layoutms
  
