 deploy_reportms:
   stage: deploy
   tags:
     - ppmrunner
 
   dependencies:
     - build_reportms
   script:
     - ls -ltr
     - podman rmi --force reportms 
     - podman rm -f reportms 
     - podman build -t reportms --build-arg WAR_FILE=reportms.war --build-arg TOMCAT_PORT=8080 -f java11file .
     - podman run -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME -e DB_HOST=$DB_HOST -e     DB_PORT=$DB_PORT -e PEP_SVN_WRITE_USERNAME=$PEP_SVN_WRITE_USERNAME -e PEP_SVN_WRITE_PASSWORD=$PEP_SVN_WRITE_PASSWORD -d --network ppm_network --name reportms -p 8098:8080 reportms 

   rules:
     - if: $CI_COMMIT_BRANCH == "ppm-dev" 
       changes:
         - reportms/**/*
   needs:
     - job: build_reportms

