 deploy_timeandexpensesms:
   stage: deploy
   tags:
     - ppmrunner
   dependencies:
     - build_timeandexpensesms 
   script:
     - ls -ltr
     - podman rmi --force timeandexpensesms 
     - podman rm -f timeandexpensesms 
     - podman build -t timeandexpensesms --build-arg WAR_FILE=timeandexpensesms.war --build-arg TOMCAT_PORT=80 -f java11file .
     - podman run -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME -e DB_HOST=$DB_HOST -e     DB_PORT=$DB_PORT -e PEP_SVN_WRITE_USERNAME=$PEP_SVN_WRITE_USERNAME -e PEP_SVN_WRITE_PASSWORD=$PEP_SVN_WRITE_PASSWORD -d --network ppm_network --name timeandexpensesms -p 9208:8080 timeandexpensesms 

   rules:
     - if: $CI_COMMIT_BRANCH == "ppm-dev"
       changes:
         - timeandexpensesms/**/*
   needs:
     - job: build_timeandexpensesms
