with open(file_path, 'rb') as file:
        encoded = base64.b64encode(file.read()).decode('utf-8')
        cacncbdkjabckjdbckwnc
        d
        cacncbdkjabckjdbckwncw'
        W'c
        WDlcwejvcilwhvcjkwebcjkwbvkbwe
        fwefwfknweclknweklcnklncwlkec
        wcwelfnwklenclwnlwe