apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: omstest
  namespace: ace-apac
  labels:
    backup.appconnect.ibm.com/component: integrationserver
spec:
  adminServerSecure: false
  annotations:
    productName: "IBM App Connect Enterprise for non-production"
    productID: ""
    productChargedContainers: "All"
    productMetric: "VIRTUAL_PROCESSOR_CORE"
    productCloudpakRatio: "2:3"
    cloudpakName: "IBM Cloud Pak for Integration"
    cloudpakId: ""
  barURL:
    - >-
     https://dev.azure.com/RL-Integration/ACE/_apis/build/builds/8752/artifacts?artifactName=output&fileId=B38F4C6EBB4FFBD38D4ED69153EFEA0A26AFBB0B8C2B32D22B64E0A0EFF923F501&fileName=dev-omsrleu-ordercreateapp.bar&api-version=7.1-preview.5
  dashboardUsers:
    bypassGenerate: false 
  designerFlowsOperationMode: disabled
  enableMetrics: false
  configurations: [ "oms-policy-project","oms-serverconf","azureartifacts-barauth"]
  labels:
    version: v1
  license:
    accept: true
    license: L-QECF-MBXVLU 
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 500m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 500Mi

  replicas: 1
  router:
    timeout: 120ms
  service:
    endpointType: http
    type: ClusterIP
  version: '12.0.12.0-r1'
