--- 
apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata: 
  name: {{ include "amenities.cnfg.ts" . }}-truststore.jks
spec: 
  data: {{ .Values.truststoreBase64 }}
  description: "Trust store"
  type: truststore
