/opt/mqm/bin/fteDeleteMonitor -mm MFTTEST  -ma AGNT.MFT.Q01.MFT01.  -mn ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST
/opt/mqm/bin/fteAnt -f ./defineMonitor.xml -Dwave="G31"  -Dmn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST"  -Dnn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST"  -Dmt="FileToDirectory.xml"  -Dmd="/tmp/in2"  -Dpt="*.csv"  -Dpi="2"  -Dpu="minutes"  -Dsa="AGNT.MFT.Q01.MFT01"  -Dsm="MFTA2HQ01"  -Dda="AGNT.MFT.Q01.MFT01"  -Ddm="MFTA2HQ01"  -Ddd="/tmp/out"  -Dsd="/tmp/"  -Dttype="binary"  -Dsrcdisp="delete"  -Dexists="overwrite"  -DmqaDeptName="OMSEU"
/opt/mqm/bin/fteAnt -f ./defineMonitor.xml -Dwave="G32"  -Dmn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST2"  -Dnn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST2"  -Dmt="FileToDirectory.xml"  -Dmd="/tmp/in"  -Dpt="*.csv"  -Dpi="2"  -Dpu="minutes"  -Dsa="AGNT.MFT.Q01.MFT01"  -Dsm="MFTA2HQ01"  -Dda="AGNT.MFT.Q01.MFT01"  -Ddm="MFTA2HQ01"  -Ddd="/tmp/out"  -Dsd="/tmp/"  -Dttype="binary"  -Dsrcdisp="delete"  -Dexists="overwrite"  -DmqaDeptName="OMSEU"
/opt/mqm/bin/fteAnt -f ./defineMonitor.xml -Dwave="G32"  -Dmn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST10"  -Dnn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST10"  -Dmt="FileToDirectory.xml"  -Dmd="/tmp/in"  -Dpt="*.csv"  -Dpi="2"  -Dpu="minutes"  -Dsa="AGNT.MFT.Q01.MFT01"  -Dsm="MFTA2HQ01"  -Dda="AGNT.MFT.Q01.MFT01"  -Ddm="MFTA2HQ01"  -Ddd="/tmp/out"  -Dsd="/tmp/"  -Dttype="binary"  -Dsrcdisp="delete"  -Dexists="overwrite"  -DmqaDeptName="OMSEU"
/opt/mqm/bin/fteAnt -f ./defineMonitor.xml -Dwave="G33"  -Dmn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST11"  -Dnn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST11"  -Dmt="FileToDirectory.xml"  -Dmd="/tmp/in"  -Dpt="*.csv"  -Dpi="2"  -Dpu="minutes"  -Dsa="AGNT.MFT.Q01.MFT01"  -Dsm="MFTA2HQ01"  -Dda="AGNT.MFT.Q01.MFT01"  -Ddm="MFTA2HQ01"  -Ddd="/tmp/out1"  -Dsd="/tmp/"  -Dttype="binary"  -Dsrcdisp="delete"  -Dexists="overwrite"  -DmqaDeptName="OMSEU"
/opt/mqm/bin/fteAnt -f ./defineMonitor.xml -Dwave="G34"  -Dmn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST12"  -Dnn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST12"  -Dmt="FileToDirectory.xml"  -Dmd="/tmp/in"  -Dpt="*.csv"  -Dpi="2"  -Dpu="minutes"  -Dsa="AGNT.MFT.Q01.MFT01"  -Dsm="MFTA2HQ01"  -Dda="AGNT.MFT.Q01.MFT01"  -Ddm="MFTA2HQ01"  -Ddd="/tmp/out"  -Dsd="/tmp/"  -Dttype="binary"  -Dsrcdisp="delete"  -Dexists="overwrite"  -DmqaDeptName="OMSEU"
/opt/mqm/bin/fteDeleteMonitor -mm MFTTEST  -ma AGNT.MFT.Q01.MFT01.  -mn ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST
/opt/mqm/bin/fteAnt -f ./defineMonitor.xml -Dwave="G31"  -Dmn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST"  -Dnn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST"  -Dmt="FileToDirectory.xml"  -Dmd="/tmp/in2"  -Dpt="*.csv"  -Dpi="2"  -Dpu="minutes"  -Dsa="AGNT.MFT.Q01.MFT01"  -Dsm="MFTA2HQ01"  -Dda="AGNT.MFT.Q01.MFT01"  -Ddm="MFTA2HQ01"  -Ddd="/tmp/out"  -Dsd="/tmp/"  -Dttype="binary"  -Dsrcdisp="delete"  -Dexists="overwrite"  -DmqaDeptName="OMSEU"
/opt/mqm/bin/fteAnt -f ./defineMonitor.xml -Dwave="G32"  -Dmn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST2"  -Dnn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST2"  -Dmt="FileToDirectory.xml"  -Dmd="/tmp/in"  -Dpt="*.csv"  -Dpi="2"  -Dpu="minutes"  -Dsa="AGNT.MFT.Q01.MFT01"  -Dsm="MFTA2HQ01"  -Dda="AGNT.MFT.Q01.MFT01"  -Ddm="MFTA2HQ01"  -Ddd="/tmp/out"  -Dsd="/tmp/"  -Dttype="binary"  -Dsrcdisp="delete"  -Dexists="overwrite"  -DmqaDeptName="OMSEU"
/opt/mqm/bin/fteAnt -f ./defineMonitor.xml -Dwave="G32"  -Dmn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST10"  -Dnn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST10"  -Dmt="FileToDirectory.xml"  -Dmd="/tmp/in"  -Dpt="*.csv"  -Dpi="2"  -Dpu="minutes"  -Dsa="AGNT.MFT.Q01.MFT01"  -Dsm="MFTA2HQ01"  -Dda="AGNT.MFT.Q01.MFT01"  -Ddm="MFTA2HQ01"  -Ddd="/tmp/out"  -Dsd="/tmp/"  -Dttype="binary"  -Dsrcdisp="delete"  -Dexists="overwrite"  -DmqaDeptName="OMSEU"
/opt/mqm/bin/fteAnt -f ./defineMonitor.xml -Dwave="G33"  -Dmn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST11"  -Dnn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST11"  -Dmt="FileToDirectory.xml"  -Dmd="/tmp/in"  -Dpt="*.csv"  -Dpi="2"  -Dpu="minutes"  -Dsa="AGNT.MFT.Q01.MFT01"  -Dsm="MFTA2HQ01"  -Dda="AGNT.MFT.Q01.MFT01"  -Ddm="MFTA2HQ01"  -Ddd="/tmp/out1"  -Dsd="/tmp/"  -Dttype="binary"  -Dsrcdisp="delete"  -Dexists="overwrite"  -DmqaDeptName="OMSEU"
/opt/mqm/bin/fteAnt -f ./defineMonitor.xml -Dwave="G34"  -Dmn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST12"  -Dnn="ACE_OMSEU_OMS_BI_PROTECTEDSTOCK_TEST12"  -Dmt="FileToDirectory.xml"  -Dmd="/tmp/in"  -Dpt="*.csv"  -Dpi="2"  -Dpu="minutes"  -Dsa="AGNT.MFT.Q01.MFT01"  -Dsm="MFTA2HQ01"  -Dda="AGNT.MFT.Q01.MFT01"  -Ddm="MFTA2HQ01"  -Ddd="/tmp/out"  -Dsd="/tmp/"  -Dttype="binary"  -Dsrcdisp="delete"  -Dexists="overwrite"  -DmqaDeptName="OMSEU"
