FROM docker.io/openjdk:8-jdk-alpine

WORKDIR /opt/dockerinstalls/APIGateway/ 
COPY ./ApiGatewayMS.jar /usr/local/lib/ApiGatewayMS.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/lib/ApiGatewayMS.jar"]
