 deploy_commonms_qa:
   stage: deploy
   tags:
    - ppm-qa
   dependencies:
    - build_commonms_qa
   script:
    - ls -ltr
    - podman rmi -f commonms
    - podman rm -f commonms
    - podman build -t commonms --build-arg WAR_FILE=commonms.war --build-arg TOMCAT_PORT=8080 -f java11file .
    - podman run -e DB_USER=$DB_USER  -e DB_PASSWORD=$DB_PASSWORD -e PEP_SVN_WRITE_USERNAME=$PEP_SVN_WRITE_USERNAME -e PEP_SVN_WRITE_PASSWORD=$PEP_SVN_WRITE_PASSWORD -e DB_NAME=$DB_NAME -e DB_HOST=$DB_HOST -e DB_PORT=$DB_PORT -d --network ppm_network --name commonms --p 9206:8080 commonms
   rules:
    - if: $CI_COMMIT_BRANCH == "ppm-qa"
      changes: 
       - commonms/**/*

