 deploy_qa_projectms:
   stage: deploy
   tags:
     - ppm-qa
   dependencies:
     - build_projectms_qa 
   script:
     - ls -ltr
     - podman rmi --force projectms 
     - podman rm -f projectms 
     - podman build -t projectms --build-arg WAR_FILE=ProjectMS.war --build-arg TOMCAT_PORT=8080 -f java11file .
     - podman run -e DB_USER=$DB_USER  -e DB_PASSWORD=$DB_PASSWORD -e PEP_SVN_WRITE_USERNAME=$PEP_SVN_WRITE_USERNAME -e PEP_SVN_WRITE_PASSWORD=$PEP_SVN_WRITE_PASSWORD -e DB_NAME=$DB_NAME -e DB_HOST=$DB_HOST -e DB_PORT=$DB_PORT -d --network ppm_network --name projectms -p 8097:8080 projectms 

   rules:
     - if: $CI_COMMIT_BRANCH == "ppm-qa" 
       changes:
         - ProjectMS/**/*
   needs:
     - job: build_projectms_qa  
