 deploy_qa_invoicems:
   stage: deploy
   tags:
     - ppm-qa
   dependencies:
     - build_invoicems_qa
   script:
     - ls -ltr
     - podman rmi --force invoicems 
     - podman rm -f invoicems 
     - podman build -t invoicems --build-arg WAR_FILE=invoicems.war --build-arg TOMCAT_PORT=8080 -f java11file .
     - podman run -e DB_USER=$DB_USER  -e DB_PASSWORD=$DB_PASSWORD -e PEP_SVN_WRITE_USERNAME=$PEP_SVN_WRITE_USERNAME -e PEP_SVN_WRITE_PASSWORD=$PEP_SVN_WRITE_PASSWORD -e DB_NAME=$DB_NAME -e DB_HOST=$DB_HOST -e DB_PORT=$DB_PORT -d --network ppm_network --name invoicems -p 8095:8080 invoicems 
   rules:
     - if: $CI_COMMIT_BRANCH == "ppm-qa" 
       changes:
         - invoicems/**/*
   needs:
     - job: build_invoicems_qa
